#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///

"""
Generate ninja build script for converting LaTeX files to AsciiDoc.

This script scans src/content for .tex files and generates a build.ninja file
that will:
- Convert .tex files to .adoc using ctfp-parse
- Copy code snippets, images, and other resources
- Copy existing .adoc files from src
- Copy fig directory

Usage:
    uv run scripts/generate_ninja.py [--output BUILD_FILE]
"""

import argparse
import os
import pathlib
from typing import List, Set


class NinjaGenerator:
    """Generate ninja build rules for the CTFP project."""

    def __init__(self, src_dir: pathlib.Path, out_dir: pathlib.Path, tools_dir: pathlib.Path):
        self.src_dir = src_dir
        self.out_dir = out_dir
        self.tools_dir = tools_dir
        self.content_dir = src_dir / "content"
        self.out_adoc_dir = out_dir / "adoc"
        self.rules: List[str] = []
        self.builds: List[str] = []
        self.all_outputs: Set[str] = set()

    def write_header(self):
        """Write ninja file header and rules."""
        self.rules.append("# Generated by scripts/generate_ninja.py")
        self.rules.append("# DO NOT EDIT MANUALLY")
        self.rules.append("")
        self.rules.append("ninja_required_version = 1.5")
        self.rules.append("")

        # Variables
        self.rules.append("# Variables")
        self.rules.append(f"srcdir = {self.src_dir}")
        self.rules.append(f"outdir = {self.out_dir}")
        self.rules.append(f"toolsdir = {self.tools_dir}")
        self.rules.append("")

        # Rule for converting tex to adoc
        self.rules.append("# Rules")
        self.rules.append("rule tex2adoc")
        self.rules.append("  command = uv run --directory $toolsdir ctfp-parse --root $in --format asciidoc --output $out")
        self.rules.append("  description = Converting $in to AsciiDoc")
        self.rules.append("")

        # Rule for copying files
        self.rules.append("rule copy")
        self.rules.append("  command = mkdir -p $$(dirname $out) && cp $in $out")
        self.rules.append("  description = Copying $in to $out")
        self.rules.append("")

    def escape_ninja_path(self, path: str) -> str:
        """Escape spaces and special characters in ninja paths."""
        return path.replace(" ", "$ ").replace(":", "$:")

    def add_tex_conversion(self, tex_file: pathlib.Path):
        """Add a build rule to convert a .tex file to .adoc."""
        # Get relative path from content directory
        rel_path = tex_file.relative_to(self.content_dir)

        # Determine the chapter directory (e.g., "1.1", "2.3", etc.)
        chapter_dir = rel_path.parts[0] if len(rel_path.parts) > 0 else ""

        # Skip language-specific subdirectories (ocaml, reason, scala)
        if chapter_dir in ["ocaml", "reason", "scala"]:
            return

        # Output file: out/adoc/<chapter>/<filename>.adoc
        adoc_filename = rel_path.stem + ".adoc"
        if len(rel_path.parts) > 1:
            # File is in a subdirectory, use just chapter name
            out_file = self.out_adoc_dir / chapter_dir / adoc_filename
        else:
            # File is at root of content
            out_file = self.out_adoc_dir / adoc_filename

        # Escape paths for ninja
        in_path = self.escape_ninja_path(str(tex_file))
        out_path = self.escape_ninja_path(str(out_file))

        self.builds.append(f"build {out_path}: tex2adoc {in_path}")
        self.all_outputs.add(str(out_file))

    def add_copy_rule(self, src_file: pathlib.Path, dest_file: pathlib.Path):
        """Add a build rule to copy a file."""
        in_path = self.escape_ninja_path(str(src_file))
        out_path = self.escape_ninja_path(str(dest_file))

        self.builds.append(f"build {out_path}: copy {in_path}")
        self.all_outputs.add(str(dest_file))

    def scan_content_resources(self, chapter_dir: pathlib.Path):
        """Scan a chapter directory for resources to copy (code, images)."""
        chapter_name = chapter_dir.name

        # Skip language-specific subdirectories at content root
        if chapter_name in ["ocaml", "reason", "scala"]:
            return

        # Copy code directory
        code_dir = chapter_dir / "code"
        if code_dir.exists() and code_dir.is_dir():
            for code_file in code_dir.rglob("*"):
                if code_file.is_file():
                    rel_path = code_file.relative_to(chapter_dir)
                    dest_file = self.out_adoc_dir / chapter_name / rel_path
                    self.add_copy_rule(code_file, dest_file)

        # Copy images directory
        images_dir = chapter_dir / "images"
        if images_dir.exists() and images_dir.is_dir():
            for image_file in images_dir.rglob("*"):
                if image_file.is_file():
                    rel_path = image_file.relative_to(chapter_dir)
                    dest_file = self.out_adoc_dir / chapter_name / rel_path
                    self.add_copy_rule(image_file, dest_file)

    def scan_content_directory(self):
        """Scan the content directory for .tex files and resources."""
        if not self.content_dir.exists():
            print(f"Warning: Content directory {self.content_dir} does not exist")
            return

        # Find all .tex files
        for tex_file in self.content_dir.rglob("*.tex"):
            self.add_tex_conversion(tex_file)

        # Scan each chapter directory for resources
        for item in self.content_dir.iterdir():
            if item.is_dir():
                self.scan_content_resources(item)

    def copy_src_adoc_files(self):
        """Copy .adoc files from src directory."""
        # List of .adoc files to copy
        adoc_files = [
            "acknowledgments.adoc",
            "colophon.adoc",
            "free-software.adoc",
            "half-title.adoc",
            "index.adoc",
            "ctfp.adoc",
        ]

        for adoc_file in adoc_files:
            src_file = self.src_dir / adoc_file
            if src_file.exists():
                dest_file = self.out_adoc_dir / adoc_file
                self.add_copy_rule(src_file, dest_file)

        # Copy editor-note.adoc from content
        editor_note = self.content_dir / "editor-note.adoc"
        if editor_note.exists():
            dest_file = self.out_adoc_dir / "content" / "editor-note.adoc"
            self.add_copy_rule(editor_note, dest_file)

    def copy_fig_directory(self):
        """Copy the fig directory."""
        fig_dir = self.src_dir / "fig"
        if fig_dir.exists() and fig_dir.is_dir():
            for fig_file in fig_dir.rglob("*"):
                if fig_file.is_file():
                    rel_path = fig_file.relative_to(self.src_dir)
                    dest_file = self.out_adoc_dir / rel_path
                    self.add_copy_rule(fig_file, dest_file)

    def copy_additional_resources(self):
        """Copy additional resources like fonts and CSS."""
        additional_files = [
            "custom.html.css",
            "Inconsolata-LGC-Bold.ttf",
        ]

        for filename in additional_files:
            src_file = self.src_dir / filename
            if src_file.exists():
                dest_file = self.out_adoc_dir / filename
                self.add_copy_rule(src_file, dest_file)

    def write_default_target(self):
        """Write the default build target."""
        self.builds.append("")
        self.builds.append("# Default target")

        # Create a list of all outputs
        output_list = " $\n    ".join(sorted(self.all_outputs))
        self.builds.append(f"build all: phony $\n    {output_list}")
        self.builds.append("")
        self.builds.append("default all")

    def generate(self, output_file: pathlib.Path):
        """Generate the complete ninja build file."""
        self.write_header()
        self.scan_content_directory()
        self.copy_src_adoc_files()
        self.copy_fig_directory()
        self.copy_additional_resources()

        # Write build rules
        self.builds.insert(0, "# Build rules")
        self.builds.insert(1, "")

        self.write_default_target()

        # Write to file
        with open(output_file, "w") as f:
            f.write("\n".join(self.rules))
            f.write("\n")
            f.write("\n".join(self.builds))
            f.write("\n")

        print(f"Generated {output_file}")
        print(f"Total outputs: {len(self.all_outputs)}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate ninja build script for CTFP LaTeX to AsciiDoc conversion",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        help="Output path for build.ninja file (default: workspace_root/build.ninja)",
    )
    parser.add_argument(
        "--src-dir",
        type=pathlib.Path,
        help="Source directory containing LaTeX files (default: workspace_root/src)",
    )
    parser.add_argument(
        "--out-dir",
        type=pathlib.Path,
        help="Output directory for generated files (default: workspace_root/out)",
    )
    parser.add_argument(
        "--tools-dir",
        type=pathlib.Path,
        help="Tools directory containing ctfp-parse (default: workspace_root/tools)",
    )

    args = parser.parse_args()

    # Get workspace root (parent of scripts directory)
    script_dir = pathlib.Path(__file__).parent
    workspace_root = script_dir.parent

    src_dir = args.src_dir or workspace_root / "src"
    out_dir = args.out_dir or workspace_root / "out"
    tools_dir = args.tools_dir or workspace_root / "tools"
    output_file = args.output or workspace_root / "build.ninja"

    generator = NinjaGenerator(src_dir, out_dir, tools_dir)
    generator.generate(output_file)


if __name__ == "__main__":
    main()
