#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///

"""
Generate ninja build script for converting LaTeX files to AsciiDoc.

This script scans src/content for .tex files and generates a build.ninja file
that will:
- Convert .tex files to .adoc using ctfp-parse
- Copy code snippets, images, and other resources
- Copy existing .adoc files from src
- Copy fig directory

Usage:
    uv run scripts/generate_ninja.py [--output BUILD_FILE]
"""

import argparse
import os
import pathlib
from typing import List, Set


class NinjaGenerator:
    """Generate ninja build rules for the CTFP project."""

    def __init__(self, src_dir: pathlib.Path, out_dir: pathlib.Path, tools_dir: pathlib.Path):
        self.src_dir = src_dir
        self.out_dir = out_dir
        self.tools_dir = tools_dir
        self.content_dir = src_dir / "content"
        self.out_adoc_dir = out_dir / "adoc"
        self.out_html_dir = out_dir / "html"
        self.rules: List[str] = []
        self.builds: List[str] = []
        self.all_outputs: Set[str] = set()
        self.adoc_outputs: Set[str] = set()  # Track .adoc files for HTML generation
        self.chapter_resources: dict = {}  # Track CSS and images for each chapter

    def write_header(self):
        """Write ninja file header and rules."""
        self.rules.append("# Generated by scripts/generate_ninja.py")
        self.rules.append("# DO NOT EDIT MANUALLY")
        self.rules.append("")
        self.rules.append("ninja_required_version = 1.5")
        self.rules.append("")

        # Variables
        self.rules.append("# Variables")
        self.rules.append(f"srcdir = {self.src_dir}")
        self.rules.append(f"outdir = {self.out_dir}")
        self.rules.append(f"toolsdir = {self.tools_dir}")
        self.rules.append("")

        # Rule for converting tex to adoc
        self.rules.append("# Rules")
        self.rules.append("rule tex2adoc")
        self.rules.append("  command = uv run --directory $toolsdir ctfp-parse --root $in --format asciidoc --output $out")
        self.rules.append("  description = Converting $in to AsciiDoc")
        self.rules.append("")

        # Rule for copying files (use reflink when possible, fallback to regular copy)
        self.rules.append("rule copy")
        self.rules.append("  command = mkdir -p $$(dirname $out) && cp --reflink=auto $in $out")
        self.rules.append("  description = Copying $in to $out")
        self.rules.append("")

        # Rule for converting adoc to html
        self.rules.append("rule adoc2html")
        self.rules.append("  command = uv run asciidoctor -r asciidoctor-diagram -r /workspace/asciidoctor-extensions/asciidoctor-latexmath/lib/asciidoctor-latexmath.rb -a pdflatex=/usr/local/texlive/2025/bin/x86_64-linux/xelatex -a stylesheet=custom.html.css -a linkcss -a data-uri -a 'source-highlighter=pygments' -a 'pygments-style=github' -o $out $in")
        self.rules.append("  description = Converting $in to HTML")
        self.rules.append("")

    def escape_ninja_path(self, path: str) -> str:
        """Escape spaces and special characters in ninja paths."""
        return path.replace(" ", "$ ").replace(":", "$:")

    def add_tex_conversion(self, tex_file: pathlib.Path):
        """Add a build rule to convert a .tex file to .adoc."""
        # Get relative path from content directory
        rel_path = tex_file.relative_to(self.content_dir)

        # Determine the chapter directory (e.g., "1.1", "2.3", etc.)
        chapter_dir = rel_path.parts[0] if len(rel_path.parts) > 0 else ""

        # Skip language-specific subdirectories (ocaml, reason, scala)
        if chapter_dir in ["ocaml", "reason", "scala"]:
            return

        # Check if a corresponding .adoc file already exists (e.g., editor-note.adoc)
        adoc_source = tex_file.with_suffix('.adoc')
        if adoc_source.exists():
            # Skip conversion, the .adoc will be copied directly
            return

        # Output file: out/adoc/content/<chapter>/<filename>.adoc
        # Keep the content/ prefix to match the directory structure
        adoc_filename = rel_path.stem + ".adoc"
        if len(rel_path.parts) > 1:
            # File is in a subdirectory, preserve content/ structure
            out_file = self.out_adoc_dir / "content" / chapter_dir / adoc_filename
        else:
            # File is at root of content
            out_file = self.out_adoc_dir / "content" / adoc_filename

        # Escape paths for ninja
        in_path = self.escape_ninja_path(str(tex_file))
        out_path = self.escape_ninja_path(str(out_file))

        self.builds.append(f"build {out_path}: tex2adoc {in_path}")
        self.all_outputs.add(str(out_file))
        self.adoc_outputs.add(str(out_file))  # Track for HTML generation

    def add_copy_rule(self, src_file: pathlib.Path, dest_file: pathlib.Path):
        """Add a build rule to copy a file."""
        in_path = self.escape_ninja_path(str(src_file))
        out_path = self.escape_ninja_path(str(dest_file))

        self.builds.append(f"build {out_path}: copy {in_path}")
        self.all_outputs.add(str(dest_file))

    def scan_content_resources(self, chapter_dir: pathlib.Path):
        """Scan a chapter directory for resources to copy (code, images)."""
        chapter_name = chapter_dir.name

        # Skip language-specific subdirectories at content root
        if chapter_name in ["ocaml", "reason", "scala"]:
            return

        # Copy code directory
        code_dir = chapter_dir / "code"
        if code_dir.exists() and code_dir.is_dir():
            for code_file in code_dir.rglob("*"):
                if code_file.is_file():
                    rel_path = code_file.relative_to(chapter_dir)
                    dest_file = self.out_adoc_dir / "content" / chapter_name / rel_path
                    self.add_copy_rule(code_file, dest_file)

        # Copy images directory
        images_dir = chapter_dir / "images"
        if images_dir.exists() and images_dir.is_dir():
            for image_file in images_dir.rglob("*"):
                if image_file.is_file():
                    rel_path = image_file.relative_to(chapter_dir)
                    dest_file = self.out_adoc_dir / "content" / chapter_name / rel_path
                    self.add_copy_rule(image_file, dest_file)

    def scan_content_directory(self):
        """Scan the content directory for .tex files and resources."""
        if not self.content_dir.exists():
            print(f"Warning: Content directory {self.content_dir} does not exist")
            return

        # Find all .tex files
        for tex_file in self.content_dir.rglob("*.tex"):
            self.add_tex_conversion(tex_file)

        # Scan each chapter directory for resources
        for item in self.content_dir.iterdir():
            if item.is_dir():
                self.scan_content_resources(item)

    def copy_src_adoc_files(self):
        """Copy .adoc files from src directory."""
        # List of .adoc files to copy from src root
        adoc_files = [
            "acknowledgments.adoc",
            "colophon.adoc",
            "free-software.adoc",
            "half-title.adoc",
            "index.adoc",
            "ctfp.adoc",
        ]

        for adoc_file in adoc_files:
            src_file = self.src_dir / adoc_file
            if src_file.exists():
                dest_file = self.out_adoc_dir / adoc_file
                self.add_copy_rule(src_file, dest_file)

        # Copy any existing .adoc files from content directory
        # (e.g., editor-note.adoc which is not generated from .tex)
        for adoc_file in self.content_dir.glob("*.adoc"):
            dest_file = self.out_adoc_dir / "content" / adoc_file.name
            self.add_copy_rule(adoc_file, dest_file)

    def copy_fig_directory(self):
        """Copy the fig directory."""
        fig_dir = self.src_dir / "fig"
        if fig_dir.exists() and fig_dir.is_dir():
            for fig_file in fig_dir.rglob("*"):
                if fig_file.is_file():
                    rel_path = fig_file.relative_to(self.src_dir)
                    dest_file = self.out_adoc_dir / rel_path
                    self.add_copy_rule(fig_file, dest_file)

    def copy_additional_resources(self):
        """Copy additional resources like fonts and CSS."""
        additional_files = [
            "custom.html.css",
            "Inconsolata-LGC-Bold.ttf",
        ]

        for filename in additional_files:
            src_file = self.src_dir / filename
            if src_file.exists():
                dest_file = self.out_adoc_dir / filename
                self.add_copy_rule(src_file, dest_file)
                # Also copy to HTML output directory for stylesheet
                if filename.endswith('.css') or filename.endswith('.ttf'):
                    html_dest_file = self.out_html_dir / filename
                    self.add_copy_rule(src_file, html_dest_file)

    def add_html_conversion(self, adoc_file: pathlib.Path, chapter_dir: str = None):
        """Add a build rule to convert a .adoc file to .html."""
        if chapter_dir:
            # Chapter HTML: out/html/content/<chapter>/<filename>.html
            html_file = self.out_html_dir / "content" / chapter_dir / adoc_file.name.replace('.adoc', '.html')
        else:
            # Main HTML: out/html/ctfp.html
            html_file = self.out_html_dir / adoc_file.name.replace('.adoc', '.html')

        in_path = self.escape_ninja_path(str(adoc_file))
        out_path = self.escape_ninja_path(str(html_file))

        # Collect implicit dependencies (CSS and images)
        implicit_deps = []
        if chapter_dir and chapter_dir in self.chapter_resources:
            implicit_deps = [self.escape_ninja_path(dep) for dep in self.chapter_resources[chapter_dir]]

        # Build rule with implicit dependencies
        if implicit_deps:
            deps_str = " ".join(implicit_deps)
            self.builds.append(f"build {out_path}: adoc2html {in_path} | {deps_str}")
        else:
            self.builds.append(f"build {out_path}: adoc2html {in_path}")
        self.all_outputs.add(str(html_file))

    def copy_images_to_html_dir(self):
        """Copy images from content directories to HTML output directories."""
        if not self.content_dir.exists():
            return

        for item in self.content_dir.iterdir():
            if item.is_dir() and item.name not in ["ocaml", "reason", "scala"]:
                chapter_name = item.name
                # Initialize resource tracking for this chapter
                if chapter_name not in self.chapter_resources:
                    self.chapter_resources[chapter_name] = []

                # Copy SVG files (diagrams) to HTML output
                for svg_file in item.glob("*.svg"):
                    dest_file = self.out_html_dir / "content" / chapter_name / svg_file.name
                    self.add_copy_rule(svg_file, dest_file)
                    self.chapter_resources[chapter_name].append(str(dest_file))

                # Add images from adoc directory as dependencies (for asciidoctor)
                images_dir = item / "images"
                if images_dir.exists() and images_dir.is_dir():
                    for image_file in images_dir.rglob("*"):
                        if image_file.is_file():
                            rel_path = image_file.relative_to(item)
                            # Images are in adoc directory, add them as dependencies
                            adoc_image = self.out_adoc_dir / "content" / chapter_name / rel_path
                            self.chapter_resources[chapter_name].append(str(adoc_image))

                            # Also copy to HTML output directory
                            html_dest_file = self.out_html_dir / "content" / chapter_name / rel_path
                            self.add_copy_rule(image_file, html_dest_file)

                # Copy code directory if it exists (for chapter-specific dependencies)
                code_dir = item / "code"
                if code_dir.exists() and code_dir.is_dir():
                    for code_file in code_dir.rglob("*"):
                        if code_file.is_file():
                            # Track code files in adoc directory as dependencies
                            rel_path = code_file.relative_to(item)
                            dest_file = self.out_adoc_dir / "content" / chapter_name / rel_path
                            # Code files are copied to adoc dir, add them as dependencies
                            self.chapter_resources[chapter_name].append(str(dest_file))

                # Copy CSS to each chapter directory for relative path access
                css_file = self.src_dir / "custom.html.css"
                if css_file.exists():
                    chapter_css = self.out_html_dir / "content" / chapter_name / "custom.html.css"
                    self.add_copy_rule(css_file, chapter_css)
                    self.chapter_resources[chapter_name].append(str(chapter_css))

    def generate_html_files(self):
        """Generate HTML files from .adoc files."""
        # Generate HTML for content chapters (from generated .adoc files)
        if self.content_dir.exists():
            for item in self.content_dir.iterdir():
                if item.is_dir() and item.name not in ["ocaml", "reason", "scala"]:
                    chapter_name = item.name
                    # Check if there's a generated .adoc file for this chapter
                    for adoc_file_path in self.adoc_outputs:
                        adoc_file = pathlib.Path(adoc_file_path)
                        # Match chapter directory pattern (e.g., content/1.1/xxx.adoc)
                        if f"/content/{chapter_name}/" in str(adoc_file):
                            self.add_html_conversion(adoc_file, chapter_name)

        # Generate main ctfp.html
        main_adoc = self.out_adoc_dir / "ctfp.adoc"
        if str(main_adoc) in self.all_outputs or main_adoc.exists():
            self.add_html_conversion(main_adoc)

    def write_default_target(self):
        """Write the default build target."""
        self.builds.append("")
        self.builds.append("# Default target")

        # Create a list of all outputs
        output_list = " $\n    ".join(sorted(self.all_outputs))
        self.builds.append(f"build all: phony $\n    {output_list}")
        self.builds.append("")
        self.builds.append("default all")

    def generate(self, output_file: pathlib.Path):
        """Generate the complete ninja build file."""
        self.write_header()
        self.scan_content_directory()
        self.copy_src_adoc_files()
        self.copy_fig_directory()
        self.copy_additional_resources()
        self.copy_images_to_html_dir()
        self.generate_html_files()

        # Write build rules
        self.builds.insert(0, "# Build rules")
        self.builds.insert(1, "")

        self.write_default_target()

        # Write to file
        with open(output_file, "w") as f:
            f.write("\n".join(self.rules))
            f.write("\n")
            f.write("\n".join(self.builds))
            f.write("\n")

        print(f"Generated {output_file}")
        print(f"Total outputs: {len(self.all_outputs)}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate ninja build script for CTFP LaTeX to AsciiDoc conversion",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        help="Output path for build.ninja file (default: workspace_root/build.ninja)",
    )
    parser.add_argument(
        "--src-dir",
        type=pathlib.Path,
        help="Source directory containing LaTeX files (default: workspace_root/src)",
    )
    parser.add_argument(
        "--out-dir",
        type=pathlib.Path,
        help="Output directory for generated files (default: workspace_root/out)",
    )
    parser.add_argument(
        "--tools-dir",
        type=pathlib.Path,
        help="Tools directory containing ctfp-parse (default: workspace_root/tools)",
    )

    args = parser.parse_args()

    # Get workspace root (parent of scripts directory)
    script_dir = pathlib.Path(__file__).parent
    workspace_root = script_dir.parent

    src_dir = args.src_dir or workspace_root / "src"
    out_dir = args.out_dir or workspace_root / "out"
    tools_dir = args.tools_dir or workspace_root / "tools"
    output_file = args.output or workspace_root / "build.ninja"

    generator = NinjaGenerator(src_dir, out_dir, tools_dir)
    generator.generate(output_file)


if __name__ == "__main__":
    main()
